### ISSUE TITLE
Class Diagrams - do we need to update with final project?

### ISSUE THREAD

**Issue by mconnell2** [mconnell2/cs400-project#17]
Something to ask Andy...

**Comment by mconnell2** [comment]
Ex. Meal.analyzeMeal - I'm thinking hashmap is better return than our earlier proposed string - easier to put discrete parts in UI.

**Comment by JulieBook0116** [comment]
I don't think we do but someone should double check with the rubric.

**Comment by mconnell2** [comment]
Not in the rubric.
